# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#   name = "github.com/x/y"
#   version = "2.4.0"
#
# [prune]
#   non-go = false
#   go-tests = true
#   unused-packages = true

[[constraint]]
  name = "github.com/jessevdk/go-flags"
  version = "1.3.0"

[[constraint]]
  name = "github.com/oklog/run"
  version = "1.0.0"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.0.4"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.2.0"

[[constraint]]
  branch = "master"
  name = "github.com/weaveworks/common"

[[override]]
  name = "k8s.io/client-go"
  version = "v8.0.0"

[[override]]
  name = "k8s.io/apimachinery"
  branch = "release-1.11"

[[constraint]]
name = "k8s.io/kubernetes"
branch = "release-1.11"

[[override]]
  name = "k8s.io/api"
  branch = "release-1.11"

[[override]]
  name = "k8s.io/apiserver"
  branch = "release-1.11"

[[override]]
  name = "k8s.io/apiextensions-apiserver"
  branch = "release-1.11"

[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  branch = "master"
  name = "github.com/getsentry/raven-go"

# Fixes:
#   vendor/k8s.io/apimachinery/pkg/runtime/serializer/json/json.go:104:3: unknown field 'CaseSensitive' in struct literal of type jsoniter.Config
# Reference:
#   https://github.com/kubernetes/kubernetes/blob/v1.11.0/Godeps/Godeps.json#L2031
[[override]]
  name = "github.com/json-iterator/go"
  revision = "f2b4162afba35581b6d4a50d3b8f34e33c144682"
 
# To use reference package:
#   vendor/k8s.io/kubernetes/pkg/util/parsers/parsers.go:36:16: undefined: reference.ParseNormalizedNamed
[[override]]
  name = "github.com/docker/distribution"
  branch = "master"

# Pin to v0.9.0-pre1 until there is a more recent stable release:
#   https://github.com/prometheus/client_golang/issues/375
[[constraint]]
  name = "github.com/prometheus/client_golang"
  version = "v0.9.0-pre1"

[[constraint]]
  name = "github.com/dlespiau/kube-test-harness"
  revision = "6dfa02a8c9926e2caffa14aa405dd699363bd9d3"

