version: 2

notify:
  webhooks:
    # Zap to forward healthcheck failures to Slack
    - url: https://hooks.zapier.com/hooks/catch/2669140/zma7dg/
    - url: https://hooks.zapier.com/hooks/catch/2669140/ziw81i/

defaults: &defaults
  working_directory: /go/src/github.com/weaveworks/launcher
  docker:
    - image: circleci/golang:latest

jobs:
  lint:
    <<: *defaults
    steps:
      - checkout
      - run: make lint

  bootstrap:
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker
      - run: make dep
      - run: go test ./bootstrap
      - run: make bootstrap
      - deploy:
          name: Push binaries to S3
          command: |
            sudo apt-get -y -qq install awscli
            aws s3 cp build/bootstrap/ s3://weaveworks-launcher/bootstrap/${CIRCLE_SHA1}/ --recursive

  service:
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker
      - run: make dep
      - run: go test ./service
      - run: make service
      - deploy:
          name: Push image
          command: |
            docker login -u "$DOCKER_REGISTRY_USER" -p "$DOCKER_REGISTRY_PASSWORD" quay.io
            if [ -z "${CIRCLE_TAG}" -a "${CIRCLE_BRANCH}" == "master" ]; then
              docker push "quay.io/weaveworks/launcher-service:$(docker/image-tag)"
              docker push "quay.io/weaveworks/launcher-service"
            else
              docker tag "quay.io/weaveworks/launcher-service:$(docker/image-tag)" "quay.io/weaveworks/build-tmp-public:launcher-service-$(docker/image-tag)"
              docker push "quay.io/weaveworks/build-tmp-public:launcher-service-$(docker/image-tag)"
            fi

  agent:
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker
      - run: make dep
      - run: go test ./agent
      - run: make agent
      - deploy:
          name: Push image
          command: |
            docker login -u "$DOCKER_REGISTRY_USER" -p "$DOCKER_REGISTRY_PASSWORD" quay.io
            if [ -z "${CIRCLE_TAG}" -a "${CIRCLE_BRANCH}" == "master" ]; then
              docker push "quay.io/weaveworks/launcher-agent:$(docker/image-tag)"
              docker push "quay.io/weaveworks/launcher-agent"
            else
              docker tag "quay.io/weaveworks/launcher-agent:$(docker/image-tag)" "quay.io/weaveworks/build-tmp-public:launcher-agent-$(docker/image-tag)"
              docker push "quay.io/weaveworks/build-tmp-public:launcher-agent-$(docker/image-tag)"
            fi

  integration_install_update_flow:
    machine: true
    environment:
      CHANGE_MINIKUBE_NONE_USER: true
    steps:
      - checkout
      - &integration_deps
        run:
          name: Install integration test dependencies
          command: |
            # Install kubectl
            curl -Lo kubectl https://storage.googleapis.com/kubernetes-release/release/v1.8.4/bin/linux/amd64/kubectl && chmod +x kubectl && sudo mv kubectl /usr/local/bin/
            # Install minikube
            curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64 && chmod +x minikube && sudo mv minikube /usr/local/bin/
            # Install yq
            curl -Lo yq https://github.com/mikefarah/yq/releases/download/1.14.0/yq_linux_amd64 && chmod +x yq && sudo mv yq /usr/local/bin/
      - run: sudo minikube start --vm-driver=none
      - run: sudo chown -R $USER.$USER ~/.minikube
      - run: sudo chown -R $USER.$USER ~/.kube
      - run: minikube update-context
      - &wait_for_minikube
        run:
          name: Wait for nodes to become ready
          command: JSONPATH='{range .items[*]}{@.metadata.name}:{range @.status.conditions[*]}{@.type}={@.status};{end}{end}'; until kubectl get nodes -o jsonpath="$JSONPATH" 2>&1 | grep -q "Ready=True"; do sleep 1; done
      - run:
          name: Execute integration tests
          command: |
            if [ -z "${CIRCLE_TAG}" -a "${CIRCLE_BRANCH}" == "master" ]; then
              export SERVICE_IMAGE="quay.io/weaveworks/launcher-service:$(docker/image-tag)"
            else
              export SERVICE_IMAGE=quay.io/weaveworks/build-tmp-public:launcher-service-$(docker/image-tag)
            fi
            ./integration-tests/tests/install-update-flow.sh

  integration_kube_system_migration:
    machine: true
    environment:
      CHANGE_MINIKUBE_NONE_USER: true
    steps:
      - checkout
      - <<: *integration_deps
      - run: sudo minikube start --vm-driver=none
      - run: sudo chown -R $USER.$USER ~/.minikube
      - run: sudo chown -R $USER.$USER ~/.kube
      - run: minikube update-context
      - <<: *wait_for_minikube
      - run:
          name: Execute integration tests
          command: |
            if [ -z "${CIRCLE_TAG}" -a "${CIRCLE_BRANCH}" == "master" ]; then
              export SERVICE_IMAGE="quay.io/weaveworks/launcher-service:$(docker/image-tag)"
            else
              export SERVICE_IMAGE=quay.io/weaveworks/build-tmp-public:launcher-service-$(docker/image-tag)
            fi
            ./integration-tests/tests/kube-system-migration.sh

  integration_flux_config:
    machine: true
    environment:
      CHANGE_MINIKUBE_NONE_USER: true
    steps:
      - checkout
      - <<: *integration_deps
      - run: sudo minikube start --vm-driver=none
      - run: sudo chown -R $USER.$USER ~/.minikube
      - run: sudo chown -R $USER.$USER ~/.kube
      - run: minikube update-context
      - <<: *wait_for_minikube
      - run:
          name: Execute integration tests
          command: |
            if [ -z "${CIRCLE_TAG}" -a "${CIRCLE_BRANCH}" == "master" ]; then
              export SERVICE_IMAGE="quay.io/weaveworks/launcher-service:$(docker/image-tag)"
            else
              export SERVICE_IMAGE=quay.io/weaveworks/build-tmp-public:launcher-service-$(docker/image-tag)
            fi
            ./integration-tests/tests/flux-config.sh

  healthcheck_dev:
    machine: true
    environment:
      CHANGE_MINIKUBE_NONE_USER: true
    steps:
      - checkout
      - <<: *integration_deps
      - run: sudo minikube start --vm-driver=none
      - run: sudo chown -R $USER.$USER ~/.minikube
      - run: sudo chown -R $USER.$USER ~/.kube
      - run: minikube update-context
      - <<: *wait_for_minikube
      - run:
          name: Execute healthcheck for get.dev.weave.works
          command: ./integration-tests/tests/healthcheck.sh get.dev.weave.works

  healthcheck_prod:
    machine: true
    environment:
      CHANGE_MINIKUBE_NONE_USER: true
    steps:
      - checkout
      - <<: *integration_deps
      - run: sudo minikube start --vm-driver=none
      - run: sudo chown -R $USER.$USER ~/.minikube
      - run: sudo chown -R $USER.$USER ~/.kube
      - run: minikube update-context
      - <<: *wait_for_minikube
      - run:
          name: Execute healthcheck for get.weave.works
          command: ./integration-tests/tests/healthcheck.sh get.weave.works

workflows:
  version: 2
  build_deploy:
    jobs:
      - lint
      - agent
      - bootstrap
      - service
      - integration_install_update_flow:
          requires:
            - agent
            - bootstrap
            - service
      - integration_kube_system_migration:
          requires:
            - agent
            - bootstrap
            - service
      - integration_flux_config:
          requires:
            - agent
            - bootstrap
            - service

  healthchecks:
    triggers:
      - schedule:
          cron: "0 * * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - healthcheck_dev
      - healthcheck_prod
