version: 2

defaults: &defaults
  working_directory: /go/src/github.com/weaveworks/launcher
  docker:
    - image: circleci/golang:latest

jobs:
  bootstrap:
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker
      - run: go get -u github.com/golang/dep/cmd/dep
      - run: cd bootstrap && dep ensure && go test
      - run: make bootstrap
      - deploy:
          name: Maybe push binaries to S3
          command: |
            if [ -z "${CIRCLE_TAG}" -a "${CIRCLE_BRANCH}" == "master" ]; then
              sudo apt-get -y -qq install awscli
              aws s3 cp build/bootstrap/ s3://weaveworks-launcher/bootstrap/$(echo $CIRCLE_SHA1 | cut -c -8)/ --recursive
            fi

  service:
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker
      - run: go get -u github.com/golang/dep/cmd/dep
      - run: cd service && dep ensure && go test
      - run: make service
      - deploy:
          name: Maybe push master image
          command: |
            if [ -z "${CIRCLE_TAG}" -a "${CIRCLE_BRANCH}" == "master" ]; then
              docker login -u "$DOCKER_REGISTRY_USER" -p "$DOCKER_REGISTRY_PASSWORD" quay.io
              docker push "quay.io/weaveworks/launcher-service:$(docker/image-tag)"
              docker push "quay.io/weaveworks/launcher-service"
            fi

  agent:
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker
      - run: go get -u github.com/golang/dep/cmd/dep
      - run: cd agent && dep ensure && go test
      - run: make agent
      - deploy:
          name: Maybe push master image
          command: |
            if [ -z "${CIRCLE_TAG}" -a "${CIRCLE_BRANCH}" == "master" ]; then
              docker login -u "$DOCKER_REGISTRY_USER" -p "$DOCKER_REGISTRY_PASSWORD" quay.io
              docker push "quay.io/weaveworks/launcher-agent:$(docker/image-tag)"
              docker push "quay.io/weaveworks/launcher-agent"
            fi

workflows:
  version: 2
  build_deploy:
    jobs:
      - agent
      - bootstrap
      - service
