version: 2

defaults: &defaults
  working_directory: /go/src/github.com/weaveworks/launcher
  docker:
    - image: circleci/golang:latest

jobs:
  lint:
    <<: *defaults
    steps:
      - checkout
      - run: make lint

  bootstrap:
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker
      - run: make dep
      - run: go test ./bootstrap
      - run: make bootstrap
      - deploy:
          name: Maybe push binaries to S3
          command: |
            if [ -z "${CIRCLE_TAG}" -a "${CIRCLE_BRANCH}" == "master" ]; then
              sudo apt-get -y -qq install awscli
              aws s3 cp build/bootstrap/ s3://weaveworks-launcher/bootstrap/${CIRCLE_SHA1}/ --recursive
            fi

  service:
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker
      - run: make dep
      - run: go test ./service
      - run: make service
      - deploy:
          name: Maybe push master image
          command: |
            if [ -z "${CIRCLE_TAG}" -a "${CIRCLE_BRANCH}" == "master" ]; then
              docker login -u "$DOCKER_REGISTRY_USER" -p "$DOCKER_REGISTRY_PASSWORD" quay.io
              docker push "quay.io/weaveworks/launcher-service:$(docker/image-tag)"
              docker push "quay.io/weaveworks/launcher-service"
            fi

  agent:
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker
      - run: make dep
      - run: go test ./agent
      - run: make agent
      - deploy:
          name: Maybe push master image
          command: |
            if [ -z "${CIRCLE_TAG}" -a "${CIRCLE_BRANCH}" == "master" ]; then
              docker login -u "$DOCKER_REGISTRY_USER" -p "$DOCKER_REGISTRY_PASSWORD" quay.io
              docker push "quay.io/weaveworks/launcher-agent:$(docker/image-tag)"
              docker push "quay.io/weaveworks/launcher-agent"
            fi

workflows:
  version: 2
  build_deploy:
    jobs:
      - lint
      - agent
      - bootstrap
      - service
