FROM nginx
EXPOSE 80
ARG version
RUN mkdir -p /usr/share/nginx/html/bootstrap/${version}
COPY ./bootstrap/* /usr/share/nginx/html/bootstrap/${version}/

LABEL maintainer="Weaveworks <help@weave.works>" \
      org.opencontainers.image.title="launcher-integration-tests" \
      org.opencontainers.image.source="https://github.com/weaveworks/launcher/tree/main/integration-tests" \
      org.opencontainers.image.revision="${version}" \
      org.opencontainers.image.vendor="Weaveworks"
