FROM alpine:3.7
LABEL maintainer="Weaveworks Inc <help@weave.works>"
RUN apk add --no-cache ca-certificates
COPY ./agent /usr/bin/launcher-agent
COPY ./kubectl /usr/bin/kubectl
ENTRYPOINT ["/usr/bin/launcher-agent"]
CMD ["-help"]
