FROM alpine:3.7
WORKDIR /
COPY service /launcher-service
RUN mkdir static
COPY static/install.sh /static/
COPY static/agent.yaml /static/
EXPOSE 80
ENTRYPOINT ["/launcher-service", "--bootstrap-version=@@GIT_HASH@@"]

ARG revision
LABEL maintainer="Weaveworks <help@weave.works>" \
      org.opencontainers.image.title="launcher-service" \
      org.opencontainers.image.source="https://github.com/weaveworks/launcher" \
      org.opencontainers.image.revision="${revision}" \
      org.opencontainers.image.vendor="Weaveworks"
