ARG base_tag
FROM weaveworks/launcher-base:${base_tag} AS build

RUN make build/.service.done

FROM alpine:3.14

COPY --from=build /go/src/github.com/weaveworks/launcher/build/service /launcher-service
RUN mkdir static
COPY --from=build /go/src/github.com/weaveworks/launcher/build/static/install.sh /static/
COPY --from=build /go/src/github.com/weaveworks/launcher/build/static/agent.yaml /static/

WORKDIR /
EXPOSE 80
ENTRYPOINT ["/launcher-service", "--bootstrap-version=@@GIT_HASH@@"]

ARG revision
LABEL maintainer="Weaveworks <help@weave.works>" \
      org.opencontainers.image.title="launcher-service" \
      org.opencontainers.image.source="https://github.com/weaveworks/launcher" \
      org.opencontainers.image.revision="${revision}" \
      org.opencontainers.image.vendor="Weaveworks"
