FROM alpine:3.7
MAINTAINER Weaveworks Inc <help@weave.works>
WORKDIR /
COPY service /launcher-service
RUN mkdir static
COPY static/install.sh /static/
COPY static/agent.yaml /static/
EXPOSE 80
ENTRYPOINT ["/launcher-service", "--bootstrap-version=@@GIT_HASH@@"]
