FROM alpine:3.7
RUN apk add --no-cache ca-certificates
COPY ./build/agent /usr/bin/launcher-agent
COPY ./build/kubectl /usr/bin/kubectl
ENTRYPOINT ["/usr/bin/launcher-agent"]
CMD ["-help"]

ARG revision
LABEL maintainer="Weaveworks <help@weave.works>" \
      org.opencontainers.image.title="launcher-agent" \
      org.opencontainers.image.source="https://github.com/weaveworks/launcher" \
      org.opencontainers.image.revision="${revision}" \
      org.opencontainers.image.vendor="Weaveworks"
